[tools]
uv = "latest"

[tasks.fmt]
run = "uv run ruff format"

[tasks.ruff]
depends = ["fmt"]
run = "uv run ruff check --fix"

[tasks.ty]
depends = ["fmt"]
run = "uv run ty check --fix"

[tasks.pytest]
depends = ["fmt"]
run = "uv run pytest"

[tasks.check]
depends = ["ruff", "ty", "pytest"]
