[project]
name = "ai-magic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "lmstudio>=1.5.0",
    "pydantic-settings>=2.12.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.4",
    "ty>=0.0.74",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff.lint]
ignore  = ["BLE001"]